export const userEmail = 'dariusz14@o2.pl';
export const passwordd = 'Password1!';
export const originDomain = 'https://magento.softwaretestingboard.com/'
export const firstName = 'Darek'
export const lastName = 'Dulemba'
export const company = "BugBusters QA"
export const street = "Krakowska 100"
export const city = "Rzeszów"
export const zipcode = "37-500"
export const countryName = "Poland"
export const phoneNumber = 721844666
export const state = "podkarpacie"
